#!/bin/sh

# Defaults
# Day: 6500K Night: 4500K

day=6500
night=3500
step=100
val=$(cat ~/.cache/lum)

rshift() {
    redshift -P -O "$1" > /dev/null 2>&1 || exit 1
    echo "$1" > ~/.cache/lum
}

case "$1" in
    u) rshift $((val + step));;

    d) rshift $((val - step));;

    D) rshift $day;;

    N) rshift $night;;
esac
