#!/bin/sh

dm() {
    dmenu -i -X 10 -Y 10 -W 1900 -p "$1"
}

[ "$1" = "-k" ] && {
    pid=$(pstree -Aap 2>/dev/null | grep -v "grep" | grep "ffmpeg.*x11" | head -n 1 | grep -o ",[0-9]\+" | sed "s/,//")
    [ -n "$pid" ] && kill "$pid" || exit 1
    echo "Killed ffmpeg with pid $pid"
} && exit

res=$(xrandr 2>/dev/null | grep -o "current.*," | sed "s/current//g; s/\s//g; s/,//g")
[ -z "$res" ] && exit 1

name="recording_$(date '+%d-%m-%y_%H%M%S')"

ext=$(printf "mp4\nwebm" | dm "Choose file type:")
[ -z "$ext" ] && exit 1

qual=$(printf "High\nNormal\nLow" | dm "Choose quality:")
[ -z "$qual" ] && exit 1

dir="$HOME/external/media/videos/screencasts"

case $qual in
    High) qual=4;;
    Normal) qual=28;;
    Low) qual=50;;
esac

case $ext in
    mp4) cdc="libx264";;
    webm) cdc="libvpx";;
esac

[ -z "$qual" ] && [ -z "$ext" ] && exit 1
setsid -f ffmpeg -y -f x11grab -s "$res" \
    -i "$DISPLAY" -c:v "$cdc" -crf "$qual" -b:v 1M "$dir/$name.$ext" >/dev/null 2>&1 &&\
    notify-send "Recording screen." "Saving in $ext format"
