#!/bin/sh

file=$(readlink -f "$1")
#dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

case $ext in
    c) gcc "$file" -o "$base" && "$base";;
    py) python "$file";;
    js) js78 "$file";;
     *) case "$(head -n 1 "$file" | cut -d / -f 3)" in
        sh) dash "$file";;
        bash) bash "$file";;
        zsh) zsh "$file";;
        *) echo "Unknown filetype.";;
    esac
esac
