#!/bin/sh

#Must be run as root

#Check if dirs are empty before
#executing mount commands
#mount -t proc /proc proc/
#mount --rbind /sys sys/
#mount --rbind /dev dev/
#mount --rbind /dev/pts dev/pts/
