#!/bin/sh

chrpath="/data/local/tmp/alpine"

ls -A $chrpath/proc 2>/dev/null && mount -t proc /proc $chrpath/proc/

#executing mount commands
#mount -t proc /proc proc/
#mount --rbind /sys sys/
#mount --rbind /dev dev/
#mount --rbind /dev/pts dev/pts/
